
#
# Makefile generated by genmkf.pl v1.0
# (c) servil 2008 <servil@gmx.net>
# made at Sun Jul 27 08:58:28 2008 for configuration: msvc-intel-release
# called with options: genmkf.pl @Makefile.specs -D PCRE_STATIC=1 -l libpcre,diaguids -t "$(IDA_SDK_ROOT)/bin/plugins/pdb.plw" -Wl debug:full,release
#

# ------------------------- basic build tools defined -------------------------
CC = cl
CXX = cl
FC = ifort
AS = ml
RSC = rc
LD = link
CVTRES = cvtres
BSC32 = bscmake
MTL = midl
RM = rm
CP = cp
MV = mv
MKDIR = mkdir
RMDIR = rmdir
ECHO = echo

# ----------------------- custom project paths defined ------------------------
IDA_ROOT = $(PROGRAMFILES)\Ida
SDKS_ROOT = C:\SDK
IDA_SDK_ROOT = $(SDKS_ROOT)\IDASDK
STLP_ROOT = $(SDKS_ROOT)/STLport
BOOST_ROOT = $(SDKS_ROOT)/boost
PCRE_ROOT = $(SDKS_ROOT)/pcre
MS_DBG_SDK_ROOT = $(PROGRAMFILES)\Debugging Tools for Windows\sdk
MSVC_ROOT = $(MSVCDIR)
MS_DIA_SDK_ROOT = $(MSVCDIR)\..\Visual Studio SDKs\DIA SDK
ICL_ROOT = $(PROGRAMFILES)\Intel\CPP\IA32

LIBPCRE = libpcre.lib

INTDIR = .
OUTDIR = $(IDA_ROOT)\plugins

# ---------------------- command line components defined ----------------------
CFLAGS = /nologo /G6 /GF /MD /LD /Gd /O1 /Ob1
CXXFLAGS = /GX /GR
FFLAGS = /MD /LD /Qvc6 /O1
DEFINES = /DNDEBUG=1 /D_WIN32_IE=0x0600 /D_WINDOWS=1 /D_WIN32=1 /DWIN32=1 \
	/DWINVER=0x0501 /D_WIN32_WINDOWS=0x0501 /D_WIN32_WINNT=0x0501 \
	/D__NT__=0x0501 /D_WINDLL=1 /D_USRDLL=1 /D_AFXDLL=1 /D_ATL_DLL=1 \
	/DHAVE_STLPORT=1 /D_STLP_USE_STATIC_LIB=1 /DBOOST_ALL_NO_LIB=1 \
	/DENUM_SOURCE=1 /DSE_XCPT_NO_SYMCLEANUP=1 /D__IDP__=1 /D__PLUGIN__=1 \
	/DPCRE_STATIC=1
UNDEFS = /U_DEBUG /U_STLP_DEBUG /U_STLP_USE_DYNAMIC_LIB
INCPATHS = /I"$(MS_DBG_SDK_ROOT)\inc" /I"$(MS_DIA_SDK_ROOT)\include" \
	/I"$(IDA_SDK_ROOT)\include" /I"$(BOOST_ROOT)" /I"$(STLP_ROOT)/stlport" \
	/I"$(PCRE_ROOT)" /I"$(ICL_ROOT)\include" /I"$(MSVC_ROOT)\include" \
	/I"$(MSVC_ROOT)\AtlMfc\include" /I"$(MSVC_ROOT)\MFC\include" \
	/I"$(MSVC_ROOT)\ATL\include"
LIBPATHS = /libpath:"$(MS_DBG_SDK_ROOT)\lib\i386" \
	/libpath:"$(MS_DIA_SDK_ROOT)\lib" /libpath:"$(BOOST_ROOT)/lib" \
	/libpath:"$(STLP_ROOT)/lib" /libpath:"$(PCRE_ROOT)" \
	/libpath:"$(ICL_ROOT)\lib" /libpath:"$(MSVC_ROOT)\lib" \
	/libpath:"$(MSVC_ROOT)\AtlMfc\lib" /libpath:"$(MSVC_ROOT)\MFC\lib"
LDFLAGS = /nologo /machine:I386 /incremental:no /subsystem:windows /dll \
	/base:0x12500000 /export:PLUGIN,DATA /release /opt:ref,icf,nowin98

# --------------------------- project files defined ---------------------------
TARBALL = $(OUTDIR)\pdb.plw
SOURCES = ./idasdk.cpp ./plugcmn.cpp ./plugcom.cpp ./plugstrm.cpp ./plugsys.cpp \
	./plugxcpt.cpp ./pcre.cpp ./md5.cpp ./pdb.cpp
OBJS = "$(INTDIR)/idasdk.obj" "$(INTDIR)/plugcmn.obj" "$(INTDIR)/plugcom.obj" \
	"$(INTDIR)/plugstrm.obj" "$(INTDIR)/plugsys.obj" "$(INTDIR)/plugtinf.obj" \
	"$(INTDIR)/plugxcpt.obj" "$(INTDIR)/pcre.obj" "$(INTDIR)/md5.obj" \
	"$(INTDIR)/pdb.obj"
LIBS = shlwapi.lib version.lib psapi.lib dbghelp.lib dbgeng.lib \
	"$(IDA_SDK_ROOT)\libvc.w32\ida.lib" $(LIBPCRE) diaguids.lib libircmt.lib \
	stlport_statix.lib kernel32.lib user32.lib advapi32.lib gdi32.lib \
	shell32.lib comctl32.lib comdlg32.lib ole32.lib oleaut32.lib winspool.lib \
	winmm.lib wsock32.lib ws2_32.lib # boost-thread.lib

# ------------------------------ targets defined ------------------------------
all: "$(TARBALL)"

"$(TARBALL)": "$(INTDIR)" $(OBJS)
	$(LD) $(OBJS) $(LIBS) $(LIBPATHS) $(LDFLAGS) /out:$@
	$(RM) -f $*.lib $*.exp
#	upx --best --lzma --strip-relocs=0 $@
	@$(ECHO) $(@F) has been built successfully.

# ----------------------------------- rules -----------------------------------
{.}.cpp{$(INTDIR)}.obj::
	$(CXX) $(CFLAGS) $(CXXFLAGS) $(INCPATHS) $(DEFINES) $(UNDEFS) /c /Fo"$(INTDIR)/" $<

# ----------------------------- file dependencies -----------------------------
"$(INTDIR)/idasdk.obj": ./idasdk.cpp ./idasdk.hpp ./undbgnew.h ./dbgnew.h \
	./plugxcpt.hpp ./plugsys.hpp ./plugtinf.obj
"$(INTDIR)/pcre.obj": ./pcre.cpp ./pcre.hpp
"$(INTDIR)/pdb.obj": ./pdb.cpp ./idasdk.hpp ./undbgnew.h ./dbgnew.h ./pcre.hpp \
	./plughlpr.hpp ./plugsys.hpp ./plugxcpt.hpp ./plugstrm.hpp ./plugtinf.hpp \
	./plugcmn.hpp ./plugcom.hpp ./pluginsn.hpp
"$(INTDIR)/plugcmn.obj": ./plugcmn.cpp ./plugcmn.hpp ./undbgnew.h ./idasdk.hpp \
	./dbgnew.h ./plugsys.hpp ./plughlpr.hpp ./pluginsn.hpp ./areaex.hpp
"$(INTDIR)/plugcom.obj": ./plugcom.cpp ./plugcom.hpp ./undbgnew.h ./idasdk.hpp \
	./dbgnew.h ./plughlpr.hpp ./plugtinf.hpp ./plugsys.hpp
"$(INTDIR)/plugstrm.obj": ./plugstrm.cpp ./pcre.hpp ./plugstrm.hpp ./undbgnew.h \
	./idasdk.hpp ./dbgnew.h ./plugsys.hpp ./plugxcpt.hpp ./plughlpr.hpp
"$(INTDIR)/plugsys.obj": ./plugsys.cpp ./plugsys.hpp ./undbgnew.h ./idasdk.hpp \
	./dbgnew.h ./plughlpr.hpp
"$(INTDIR)/plugtinf.obj": ./plugtinf.cpp ./plugtinf.hpp ./undbgnew.h \
	./idasdk.hpp ./dbgnew.h ./plughlpr.hpp
"$(INTDIR)/plugxcpt.obj": ./plugxcpt.cpp ./plugxcpt.hpp ./undbgnew.h \
	./plugsys.hpp ./idasdk.hpp ./dbgnew.h ./plughlpr.hpp
"$(INTDIR)/md5.obj": ./md5.cpp

"$(INTDIR)":
	$(MKDIR) $@

clean:
	$(RM) -f $(OBJS) .\vc60.?db .\icl.pchi

!IF EXISTS("./deps.mak")
!INCLUDE ./deps.mak
!ENDIF
